In [6]:
'''importing required lib'''
import numpy as np # to deal with numbers and array
import pandas as pd #for handling dataframes
from sklearn.utils import shuffle #use to shuffle dataframe

''' lib required for creating a model  i.e text data into array of matrix'''
from sklearn.feature_extraction.text import CountVectorizer  ## BOW Model
from sklearn.feature_extraction.text import TfidfVectorizer  ## TFIDF Model
# for converting text data into array 

''' lib required for cleaning of data'''
from nltk.corpus import stopwords #containing stopwords
from nltk.stem.porter import PorterStemmer # use to fing a core meaning of words 
from nltk.stem.wordnet import WordNetLemmatizer
import re #used for regular expression operation
import os

'''Algorithms used
naivebayes>>>MultinomialNB ,BernoulliNB
linear_model>>>>>Logistic regression ,SGDClassifier, 
SVM>>>>SVC ,LinearSVC ,NuSVC
RandomForest
'''

'Algorithms used\nnaivebayes>>>MultinomialNB ,BernoulliNB\nlinear_model>>>>>Logistic regression ,SGDClassifier, \nSVM>>>>SVC ,LinearSVC ,NuSVC\nRandomForest\n'

In [7]:
''' dataset will be collected form https://www.crisisNLP.com
d1=pd.read_csv("2015_Nepal.csv")
d2=pd.read_csv("2014_India_floods.csv")
d3=pd.read_csv("typ.csv")
d4=pd.read_csv("pakistan_flood.csv")
d5=pd.read_csv("cyclone_plam.csv")
d6=pd.read_csv("2014_MERS.csv")
d7=pd.read_csv("2014_hurrican.csv")
d8=pd.read_csv("2014_ebola.csv")
d9=pd.read_csv("2014_chile_earthquake.csv")
d10=pd.read_csv("2014_california_earthquake.csv")
d11=pd.read_csv("2013_pakistaan_eq_cf.csv")'''
dataframe=pd.read_csv('crisis1.csv',encoding = 'unicode_escape')

In [8]:
#dataframe=pd.concat([d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11],ignore_index=True)
#concating all the dataframes

In [9]:
dataframe.head() #showing first five values

Unnamed: 0                                              label  \
0           0                           other_useful_information   
1           1                    missing_trapped_or_found_people   
2           2                             injured_or_dead_people   
3           3  donation_needs_or_offers_or_volunteering_services   
4           4                           other_useful_information   

               tweet_id                                         tweet_text  
0  '592326564110585856'  RT @divyaconnects: Reached #Kathmandu finally!...  
1  '592616512642420737'  fears for Foreigners missing in Nepal earthqua...  
2  '592686635520827393'  RT @ParisBurned: 3,700 people dead is absolute...  
3  '593301431366635520'  Earthquake in Nepal - Please help Kapil #crowd...  
4  '592590231519555584'  Nepal’s Slowing Economy Set for Freefall Witho...

In [10]:
del dataframe['Unnamed: 0']

In [11]:
dataframe.shape # describing the size of dataframe

(20624, 3)

In [12]:
dataframe.columns #information about the attributes

Index(['label', 'tweet_id', 'tweet_text'], dtype='object')

In [13]:
dataframe.describe() # describe the dataframe internal information

label              tweet_id  \
count                      20624                 20624   
unique                        15                 18743   
top     other_useful_information  '383910852254244864'   
freq                        6231                     2   

                                               tweet_text  
count                                               20624  
unique                                              18743  
top     #earthquake #NZ: Magnitude 2.4, Thursday, Sept...  
freq                                                    2

In [14]:
dataframe.isnull().sum() #determining whether there is a empty value is present or not

label         0
tweet_id      0
tweet_text    0
dtype: int64

In [15]:
dataframe['label'].unique()

array(['other_useful_information', 'missing_trapped_or_found_people',
       'injured_or_dead_people',
       'donation_needs_or_offers_or_volunteering_services',
       'sympathy_and_emotional_support', 'not_related_or_irrelevant',
       'caution_and_advice', 'displaced_people_and_evacuations',
       'infrastructure_and_utilities_damage', 'prevention',
       'disease_transmission', 'deaths_reports',
       'disease_signs_or_symptoms', 'affected_people', 'treatment'],
      dtype=object)

In [16]:
label1={'other_useful_information':1, 'missing_trapped_or_found_people':2,
       'injured_or_dead_people':3,
       'donation_needs_or_offers_or_volunteering_services':4,
       'sympathy_and_emotional_support':5, 'not_related_or_irrelevant':6,
       'caution_and_advice':7, 'displaced_people_and_evacuations':8,
       'infrastructure_and_utilities_damage':9, 'prevention':10,
       'disease_transmission':11, 'deaths_reports':12,
       'disease_signs_or_symptoms':13, 'affected_people':14, 'treatment':15}
def label(x):
    return label1[x];

In [17]:
dataframe["numeric_label"]=dataframe["label"].map(label)

In [18]:
dataframe['label'].value_counts() # number of events with there count 

other_useful_information                             6231
not_related_or_irrelevant                            2758
injured_or_dead_people                               2427
donation_needs_or_offers_or_volunteering_services    2288
sympathy_and_emotional_support                       1875
infrastructure_and_utilities_damage                  1336
caution_and_advice                                   1029
affected_people                                       551
displaced_people_and_evacuations                      474
treatment                                             370
disease_signs_or_symptoms                             346
disease_transmission                                  336
missing_trapped_or_found_people                       277
prevention                                            253
deaths_reports                                         73
Name: label, dtype: int64

In [19]:
print(dataframe['tweet_text'][5])
print("event extracted>>>")
print(dataframe['label'][5])
'''tweet with corresponding label'''

RT @cuteinsan: In this horrible situation in nepal our God  @Gurmeetramrahim  can help pita ji they really need your simpathy #MSGHelpEarth…
event extracted>>>
sympathy_and_emotional_support


'tweet with corresponding label'

In [20]:
dataframe['tweet_id'].nunique() #number of unique tweet ID

18743

In [21]:
#Term frequency inverse document freq before preprocessing
#tf_idf_vect = TfidfVectorizer()
#tf_idf = tf_idf_vect.fit_transform(dataframe['tweet_text'].values)
#tf_idf.shape
# it's showing very high value of feature preprocessing is required

In [22]:
'''
from nltk.corpus import stopwords #containing stopwords
from nltk.stem.porter import PorterStemmer # use to fing a core meaning of words 
from nltk.stem.wordnet import WordNetLemmatizer
import re #used for regular expression operation
import os '''

'\nfrom nltk.corpus import stopwords #containing stopwords\nfrom nltk.stem.porter import PorterStemmer # use to fing a core meaning of words \nfrom nltk.stem.wordnet import WordNetLemmatizer\nimport re #used for regular expression operation\nimport os '

In [23]:
stop_words = set(stopwords.words('english'))
print(stop_words)

{"wouldn't", 'any', 'further', 'a', 'mightn', 'themselves', "mightn't", 'his', 'than', 'as', "aren't", 'up', 'o', 'while', 'their', 'by', 'herself', 'the', 've', 'will', 'very', 'down', 'has', 'in', 'her', 'about', 'me', "you're", 'ourselves', "haven't", 're', 'needn', 'do', 'he', 'but', "mustn't", "you'll", 'both', 'some', 'nor', 'below', 'yourself', 'out', 'couldn', 'into', "won't", 'during', 'just', 'few', "doesn't", 'this', 'ma', 'before', 'was', 'is', 'to', 'we', 'once', "didn't", "it's", 'being', 'until', 'how', 'you', 'what', 'am', 'most', 'of', 'mustn', 'against', "needn't", 'it', 'if', 'under', 'own', 'll', 'who', "shan't", 'our', 'were', 'didn', "you've", 'other', 'i', 'd', 'no', 'y', 'doesn', "she's", 'then', 'such', "that'll", 'wouldn', "hasn't", 'doing', 'and', "should've", 'after', "hadn't", 'again', 's', 'that', 'only', 'yours', 'are', 'does', 'when', 'been', 'here', 'which', 'hadn', 'on', 'off', "wasn't", 'so', "weren't", 'did', "don't", 'from', 'now', 't', 'those', 'th

In [24]:
new_words = ["RT",'rt'] #creating a list of extra stop words
stop_words = stop_words.union(new_words) #adding words into corpus

In [25]:
'''
Input : The whole dataframe will be send to the function
Output : Column with clean tweets tweet will be added
Function perform following operation:
       1. Clean text from html tags
       2. Clean text from punctuations and special characters
       3. Retain only non-numeric Latin characters with lenght > 2
       4. Remove stopwords from the sentence
       5. Apply stemming to all the words in the sentence
'''
def clean_tweets(dataset):
    corpus = []
    for i in range(0, dataset.shape[0]):
        text=dataset['tweet_text'][i]
        #hte line data.shape will return [row size,columnsize ] from which we are taking row size using index 0
        
        #remove @mentions
        rg=re.compile('@[^, ]*\s*')
        text=re.sub(rg," ",text)

        #remove urls
        rg=re.compile('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+')
        text=re.sub(rg," ",text)

        #Remove punctuations
        text = re.sub('[^a-zA-Z0-9]', ' ',text)

        #Convert to lowercase
        text = text.lower()

        #remove tags
        text=re.sub("&lt;/?.*?&gt;"," &lt;&gt; ",text)

        # remove special characters and digits
        #text=re.sub("(\\d|\\W)+"," ",text)
        text=re.sub("(\\W)+"," ",text)

        ##Convert to list from string
        text = text.split()

        ##Stemming
        ps=PorterStemmer()    #Lemmatisation
        lem = WordNetLemmatizer()
        text = [lem.lemmatize(word) for word in text if not word in
                stop_words]
        text = " ".join(text)
        corpus.append(text)
    dataset['preprocessed']=corpus
    return dataset

In [26]:
dataframe=clean_tweets(dataframe)# function calling for preprocessed tweet
dataframe.head()

label              tweet_id  \
0                           other_useful_information  '592326564110585856'   
1                    missing_trapped_or_found_people  '592616512642420737'   
2                             injured_or_dead_people  '592686635520827393'   
3  donation_needs_or_offers_or_volunteering_services  '593301431366635520'   
4                           other_useful_information  '592590231519555584'   

                                          tweet_text  numeric_label  \
0  RT @divyaconnects: Reached #Kathmandu finally!...              1   
1  fears for Foreigners missing in Nepal earthqua...              2   
2  RT @ParisBurned: 3,700 people dead is absolute...              3   
3  Earthquake in Nepal - Please help Kapil #crowd...              4   
4  Nepal’s Slowing Economy Set for Freefall Witho...              1   

                                        preprocessed  
0  reached kathmandu finally lot indian stranded ...  
1  fear foreigner missing nepal earthquake death ...  
2  3 700 people dead absolutely devastating count...  
3  earthquake nepal please help kapil crowdfundin...  
4  nepal slowing economy set freefall without wor...

In [27]:
print(dataframe['tweet_text'][2])
print('After preprocessing>>>>>>>>>>>>>>>>>')
print(dataframe['preprocessed'][2])

RT @ParisBurned: 3,700 people dead is absolutely devastating for a country that is the size of Oklahoma on the map. #Nepal
After preprocessing>>>>>>>>>>>>>>>>>
3 700 people dead absolutely devastating country size oklahoma map nepal


In [28]:

X = dataframe['preprocessed'].values# text data will be converted into operational format
y=dataframe['numeric_label'].values #same as it is'''
print(X[0:5])
print('corresponding result >>>>>>>>>>>>>>>>>>>>')
print(y[0:5])


['reached kathmandu finally lot indian stranded airport nepalquake'
 'fear foreigner missing nepal earthquake death toll soar'
 '3 700 people dead absolutely devastating country size oklahoma map nepal'
 'earthquake nepal please help kapil crowdfunding fundrazr support retweet via mechanismofwar'
 'nepal slowing economy set freefall without world help via']
corresponding result >>>>>>>>>>>>>>>>>>>>
[1 2 3 4 1]


In [29]:
tf_idf_vect = TfidfVectorizer()# initializing the vector by creating object
X= tf_idf_vect.fit_transform(X) # tranforming text data into vector format
X.shape

(20624, 18961)

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 123)

In [32]:
from sklearn import metrics

In [27]:
from sklearn.ensemble import RandomForestClassifier

In [45]:
random_forest_model=RandomForestClassifier(n_estimators=400, max_depth=5, random_state=0)

In [46]:
random_forest_model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=5, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=400,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [47]:
y_pred=random_forest_model.predict(X_test)#after training we pass rest 20%of data for testing purpose
y_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [48]:
acc=metrics.accuracy_score(y_test,y_pred) 
#here we are passing actual result and predicted result to find out accuracy
print('acuuracy>>>>',acc*100)

acuuracy>>>> 29.762481822588466


In [33]:
from xgboost import XGBClassifier

In [48]:
model=XGBClassifier()

In [49]:
from time import time
start_time=time()
model.fit(X_train,y_train)
print("--- %s seconds ---" % (time() - start_time))

--- 241.43729829788208 seconds ---


In [50]:
y_pred=model.predict(X_test)#after training we pass rest 20%of data for testing purpose
y_pred

array([7, 3, 1, ..., 5, 6, 1], dtype=int64)

In [51]:
acc=metrics.accuracy_score(y_test,y_pred) 
#here we are passing actual result and predicted result to find out accuracy
print('acuuracy>>>>',acc*100)

acuuracy>>>> 69.36500242365487


In [1]:
from time import ctime

In [38]:
starttime=ctime()

In [39]:
print(starttime)

Sat Feb 22 17:27:43 2020
